/*! 
 * SAPUI5

		(c) Copyright 2009-2021 SAP SE. All rights reserved
	 
 */
(function(){
/*!
 * SAPUI5

		(c) Copyright 2009-2021 SAP SE. All rights reserved
	
 */
sap.ui.define(["../core/util","./Sina","../providers/abap_odata/Provider","../providers/hana_odata/Provider","../providers/sample/Provider","../providers/inav2/Provider","../providers/dummy/Provider","../providers/multi/Provider","../core/Log","../core/errors","./SinaConfiguration","./i18n"],function(e,r,n,o,t,i,s,c,a,u,d,l){"use strict";const v=r["Sina"];const f=n["Provider"];const g=o["Provider"];const p=t["Provider"];const A=i["Provider"];const P=s["Provider"];const w=c["MultiProvider"];const h=u["NoValidEnterpriseSearchAPIConfigurationFoundError"];const b=d["AvailableProviders"];const y=d["_normalizeConfiguration"];const L=l["injectGetText"];if(typeof process!=="undefined"&&process.env&&process.env.NODE_ENV&&process.env.NODE_ENV==="debug"){const e=new a.Log;a.Log.level=a.Severity.DEBUG;e.debug("SINA log level set to debug!")}async function M(e){const r=await y(e);if(r.getText){L(r.getText)}if(r.logTarget){a.Log.persistency=r.logTarget}if(typeof r.logLevel!=="undefined"){a.Log.level=r.logLevel}const n=new a.Log("sinaFactory");n.debug("Creating new sina (esh client) instance using provider "+r.provider);let o;switch(r.provider){case b.HANA_ODATA:{o=new g;break}case b.ABAP_ODATA:{o=new f;break}case b.INAV2:{o=new A;break}case b.MULTI:{o=new w;break}case b.SAMPLE:{o=new p;break}case b.DUMMY:{o=new P;break}default:{throw new Error("Unknown Provider: '"+r.provider+"' - Available Providers: "+b.HANA_ODATA+", "+b.ABAP_ODATA+", "+b.INAV2+", "+b.MULTI+", "+b.SAMPLE+", "+b.DUMMY)}}const t=new v(o);await t.initAsync(r);return t}function T(e,r){let n;return Promise.all(e.map(y.bind(this))).then(function(e){n=e;return D(n)}.bind(this)).then(function(){return _(n,r)}.bind(this))}async function m(){const r=e.getUrlParameter("sinaConfiguration");if(r){return y(r)}const n=e.getUrlParameter("sinaProvider");if(n){return y(n)}return Promise.resolve()}async function _(e,r){const n=new a.Log("sinaFactory");const o=[];r=r||function(){return true};const t=[];const i=function(s){if(s>=e.length){let e;if(o.length>=1){e=new h(t.join(", "),o[o.length-1].error)}else{e=new h(t.join(", "))}return Promise.reject(e)}const c=e[s];t.push(c.provider);return M(c).then(function(e){if(r(e)){return e}return i(s+1)},function(e){n.info(e);o.push({index:s,error:e});return i(s+1)})}.bind(this);return i(0)}async function D(e){const r=await m();if(!r){return}if(e.length===1){E(e[0],r);return}else{let n=false;for(let o=0;o<e.length;++o){const t=e[o];if(t.provider===b.DUMMY){continue}if(t.provider!==r.provider){e.splice(o,1);o--;continue}n=true;E(t,r)}if(!n){e.splice(0,0,r)}}}function E(e,r){for(const n in r){e[n]=r[n]}}var N={__esModule:true};N.createAsync=M;N.createByTrialAsync=T;return N})})();
//# sourceMappingURL=sinaFactory.js.map