/*!
 * 
		SAP UI development toolkit for HTML5 (SAPUI5)
        (c) Copyright 2009-2021 SAP SE. All rights reserved
	
 */
const aCustomerData = [
	{
		Customer: "0",
		SalesOrganization: "1000",
		DistributionChannel: "10",
		Division: "00",
		PartnerCounter: "",
		IBAN: "",
		CardNumber: "2919682",
		PaymentCardType: "",
		BusinessPartnerName: " iurhgiurhgiurehgure Mehta",
		CityName: "Bangalore",
		PhoneNumber: "12345",
		EmailAddress: "fgy@xyz.example",
		DunningProcedure: "",
		DunningBlock: "",
		CustomerAccountGroup: "DEBI",
		AccountGroupName: "Customer (general)",
		FirstName: "Robert",
		LastName: "lewandowski",
		OrganizationBPName1: "",
		OrganizationBPName2: "",
		GroupBusinessPartnerName1: "",
		GroupBusinessPartnerName2: "",
		BusinessPartnerType: "",
		LegalForm: "",
		LegalEntityOfOrganization: "",
		BusinessPartnerIDByExtSystem: "",
		IsMarkedForArchiving: false,
		BusinessPartnerIsBlocked: true,
		ContactPermission: "",
		StreetName: "ABC street",
		PostalCode: "123456",
		Country: "IN",
		Region: "",
		AddressTimeZone: "INDIA",
		POBox: "123",
		POBoxPostalCode: "54678",
		CompanyPostalCode: "",
		CorrespondenceLanguage: "EN",
		MobilePhoneNumber: "+5398706543",
		FaxNumber: "",
		PrfrdCommMediumType: "INT",
		SearchTerm1: "MEHTA",
		SearchTerm2: "",
		Supplier: "",
		PostingIsBlocked: false,
		AuthorizationGroup: "",
		CreatedByUser: "PARMARDE",
		ImageUrl: "sap-icon://building",
		TotalNetAmount: 397905,
		TransactionCurrency: "USD",
		Rating: 1,
		Progress: 50,
		OverallStatus: "A",
		StatusCriticality: 0,
		CreditScore: 600,
		LastCustomerContactDate: "2021-08-09"
	},
	{
		Customer: "1",
		SalesOrganization: "1010",
		DistributionChannel: "01",
		Division: "01",
		PartnerCounter: "",
		IBAN: "",
		CardNumber: "2922870",
		PaymentCardType: "",
		BusinessPartnerName: "Filiale Homburg1",
		CityName: "Homburg",
		PhoneNumber: "06841 12546",
		EmailAddress: "",
		DunningProcedure: "",
		DunningBlock: "",
		CustomerAccountGroup: "DEBI",
		AccountGroupName: "Customer (general)",
		FirstName: "Cristiano",
		LastName: "Ronaldo",
		OrganizationBPName1: "Filiale Homburg1",
		OrganizationBPName2: "",
		GroupBusinessPartnerName1: "",
		GroupBusinessPartnerName2: "",
		BusinessPartnerType: "",
		LegalForm: "",
		LegalEntityOfOrganization: "",
		BusinessPartnerIDByExtSystem: "",
		IsMarkedForArchiving: false,
		BusinessPartnerIsBlocked: true,
		ContactPermission: "",
		StreetName: "Hauptstaße",
		PostalCode: "66424",
		Country: "DE",
		Region: "10",
		AddressTimeZone: "CET",
		POBox: "12343",
		POBoxPostalCode: "12344",
		CompanyPostalCode: "",
		CorrespondenceLanguage: "DE",
		MobilePhoneNumber: "",
		FaxNumber: "TYI788",
		PrfrdCommMediumType: "",
		SearchTerm1: "FILIALE HOMBURG",
		SearchTerm2: "",
		Supplier: "",
		PostingIsBlocked: false,
		AuthorizationGroup: "",
		CreatedByUser: "BRECHTELJ",
		ImageUrl: "sap-icon://lead",
		TotalNetAmount: 123456,
		TransactionCurrency: "USD",
		Rating: 2,
		Progress: 60,
		OverallStatus: "B",
		StatusCriticality: 1,
		CreditScore: 700,
		LastCustomerContactDate: "2021-08-08"
	},
	{
		Customer: "2",
		SalesOrganization: "1210",
		DistributionChannel: "20",
		Division: "02",
		PartnerCounter: "",
		IBAN: "",
		CardNumber: "2915717",
		PaymentCardType: "",
		BusinessPartnerName: "My Company5 (JH)",
		CityName: "My Cit6",
		PhoneNumber: "",
		EmailAddress: "",
		DunningProcedure: "",
		DunningBlock: "",
		CustomerAccountGroup: "DEBI",
		AccountGroupName: "Customer (general)",
		FirstName: "Lionel",
		LastName: "Messi",
		OrganizationBPName1: "My Company5 (JH)",
		OrganizationBPName2: "",
		GroupBusinessPartnerName1: "",
		GroupBusinessPartnerName2: "",
		BusinessPartnerType: "",
		LegalForm: "08",
		LegalEntityOfOrganization: "",
		BusinessPartnerIDByExtSystem: "",
		IsMarkedForArchiving: false,
		BusinessPartnerIsBlocked: true,
		ContactPermission: "",
		StreetName: "",
		PostalCode: "44444",
		Country: "DE",
		Region: "10",
		AddressTimeZone: "CET",
		POBox: "",
		POBoxPostalCode: "",
		CompanyPostalCode: "",
		CorrespondenceLanguage: "DE",
		MobilePhoneNumber: "",
		FaxNumber: "",
		PrfrdCommMediumType: "",
		SearchTerm1: "JH",
		SearchTerm2: "",
		Supplier: "",
		PostingIsBlocked: false,
		AuthorizationGroup: "",
		CreatedByUser: "HAUPENTHAL",
		ImageUrl: "sap-icon://lab",
		TotalNetAmount: 234519,
		TransactionCurrency: "EUR",
		Rating: 3,
		Progress: 70,
		OverallStatus: "A",
		StatusCriticality: 2,
		CreditScore: 800,
		LastCustomerContactDate: "2021-08-07"
	},
	{
		Customer: "3",
		SalesOrganization: "1530",
		DistributionChannel: "02",
		Division: "00",
		PartnerCounter: "",
		IBAN: "",
		CardNumber: "2916499",
		PaymentCardType: "",
		BusinessPartnerName: "Toll Industries Customer",
		CityName: "Walldorf",
		PhoneNumber: "09123 12312333",
		EmailAddress: "back.stage@xyz.example",
		DunningProcedure: "",
		DunningBlock: "",
		CustomerAccountGroup: "DEBI",
		AccountGroupName: "Customer (general)",
		FirstName: "Harry",
		LastName: "Kane",
		OrganizationBPName1: "Toll Industries Customer",
		OrganizationBPName2: "",
		GroupBusinessPartnerName1: "",
		GroupBusinessPartnerName2: "",
		BusinessPartnerType: "",
		LegalForm: "",
		LegalEntityOfOrganization: "",
		BusinessPartnerIDByExtSystem: "",
		IsMarkedForArchiving: false,
		BusinessPartnerIsBlocked: true,
		ContactPermission: "",
		StreetName: "Nebengasse",
		PostalCode: "69190",
		Country: "DE",
		Region: "",
		AddressTimeZone: "CET",
		POBox: "",
		POBoxPostalCode: "",
		CompanyPostalCode: "",
		CorrespondenceLanguage: "DE",
		MobilePhoneNumber: "+49934234234234",
		FaxNumber: "08837",
		PrfrdCommMediumType: "",
		SearchTerm1: "ACR",
		SearchTerm2: "",
		Supplier: "",
		PostingIsBlocked: false,
		AuthorizationGroup: "",
		CreatedByUser: "CORNELIUSRI",
		ImageUrl: "sap-icon://building",
		TotalNetAmount: 321.56,
		TransactionCurrency: "EUR",
		Rating: 4,
		Progress: 80,
		OverallStatus: "B",
		StatusCriticality: 3,
		CreditScore: 900,
		LastCustomerContactDate: "2021-08-06"
	},
	{
		Customer: "6",
		SalesOrganization: "2010",
		DistributionChannel: "01",
		Division: "11",
		PartnerCounter: "",
		IBAN: "",
		CardNumber: "2917844",
		PaymentCardType: "",
		BusinessPartnerName: "Toll Industries Customer",
		CityName: "Walldorf",
		PhoneNumber: "09123 12312333",
		EmailAddress: "back.stage@xyz.example",
		DunningProcedure: "",
		DunningBlock: "",
		CustomerAccountGroup: "DEBI",
		AccountGroupName: "Customer (general)",
		FirstName: "Kylian",
		LastName: "Mbappe",
		OrganizationBPName1: "Toll Industries Customer",
		OrganizationBPName2: "",
		GroupBusinessPartnerName1: "",
		GroupBusinessPartnerName2: "",
		BusinessPartnerType: "",
		LegalForm: "",
		LegalEntityOfOrganization: "",
		BusinessPartnerIDByExtSystem: "",
		IsMarkedForArchiving: false,
		BusinessPartnerIsBlocked: false,
		ContactPermission: "",
		StreetName: "Nebengasse",
		PostalCode: "69190",
		Country: "DE",
		Region: "",
		AddressTimeZone: "CET",
		POBox: "",
		POBoxPostalCode: "",
		CompanyPostalCode: "",
		CorrespondenceLanguage: "DE",
		MobilePhoneNumber: "+49934234234234",
		FaxNumber: "08837",
		PrfrdCommMediumType: "",
		SearchTerm1: "ACR",
		SearchTerm2: "",
		Supplier: "",
		PostingIsBlocked: false,
		AuthorizationGroup: "",
		CreatedByUser: "CORNELIUSRI",
		ImageUrl: "sap-icon://lead",
		TotalNetAmount: 71245,
		TransactionCurrency: "USD",
		Rating: 5,
		Progress: 90,
		OverallStatus: "C",
		StatusCriticality: 0,
		CreditScore: 400,
		LastCustomerContactDate: "2021-08-05"
	},
	{
		Customer: "11",
		SalesOrganization: "3010",
		DistributionChannel: "20",
		Division: "00",
		PartnerCounter: "",
		IBAN: "",
		CardNumber: "2919431",
		PaymentCardType: "",
		BusinessPartnerName: " Test",
		CityName: "Ludwigshafen",
		PhoneNumber: "9187383",
		EmailAddress: "asd@xyz.example",
		DunningProcedure: "",
		DunningBlock: "",
		CustomerAccountGroup: "DEBI",
		AccountGroupName: "Customer (general)",
		FirstName: "Pogba",
		LastName: "Test",
		OrganizationBPName1: "",
		OrganizationBPName2: "",
		GroupBusinessPartnerName1: "",
		GroupBusinessPartnerName2: "",
		BusinessPartnerType: "",
		LegalForm: "",
		LegalEntityOfOrganization: "",
		BusinessPartnerIDByExtSystem: "",
		IsMarkedForArchiving: false,
		BusinessPartnerIsBlocked: false,
		ContactPermission: "",
		StreetName: "",
		PostalCode: "67063",
		Country: "DE",
		Region: "07",
		AddressTimeZone: "CET",
		POBox: "",
		POBoxPostalCode: "",
		CompanyPostalCode: "",
		CorrespondenceLanguage: "EN",
		MobilePhoneNumber: "",
		FaxNumber: "",
		PrfrdCommMediumType: "",
		SearchTerm1: "SEARCH",
		SearchTerm2: "",
		Supplier: "",
		PostingIsBlocked: false,
		AuthorizationGroup: "",
		CreatedByUser: "CORNELIUSRI",
		ImageUrl: "sap-icon://lab",
		TotalNetAmount: 89012,
		TransactionCurrency: "GBP",
		Rating: 1,
		Progress: 10,
		OverallStatus: "A",
		StatusCriticality: 1,
		CreditScore: 300,
		LastCustomerContactDate: "2021-08-04"
	},
	{
		Customer: "13",
		SalesOrganization: "4100",
		DistributionChannel: "01",
		Division: "01",
		PartnerCounter: "",
		IBAN: "",
		CardNumber: "2922872",
		PaymentCardType: "",
		BusinessPartnerName: "ChemComp",
		CityName: "Markdorf",
		PhoneNumber: "",
		EmailAddress: "m.schalk@xyz.example",
		DunningProcedure: "",
		DunningBlock: "",
		CustomerAccountGroup: "DEBI",
		AccountGroupName: "Customer (general)",
		FirstName: "Sergio",
		LastName: "Ramos",
		OrganizationBPName1: "ChemComp",
		OrganizationBPName2: "",
		GroupBusinessPartnerName1: "",
		GroupBusinessPartnerName2: "",
		BusinessPartnerType: "",
		LegalForm: "",
		LegalEntityOfOrganization: "",
		BusinessPartnerIDByExtSystem: "",
		IsMarkedForArchiving: false,
		BusinessPartnerIsBlocked: false,
		ContactPermission: "",
		StreetName: "Dornierstrasse",
		PostalCode: "88677",
		Country: "DE",
		Region: "",
		AddressTimeZone: "CET",
		POBox: "",
		POBoxPostalCode: "",
		CompanyPostalCode: "",
		CorrespondenceLanguage: "EN",
		MobilePhoneNumber: "",
		FaxNumber: "",
		PrfrdCommMediumType: "INT",
		SearchTerm1: "CHEMCOMP",
		SearchTerm2: "",
		Supplier: "",
		PostingIsBlocked: false,
		AuthorizationGroup: "",
		CreatedByUser: "SCHALKM",
		ImageUrl: "sap-icon://building",
		TotalNetAmount: 888,
		TransactionCurrency: "ADP",
		Rating: 2,
		Progress: 20,
		OverallStatus: "B",
		StatusCriticality: 2,
		CreditScore: 600,
		LastCustomerContactDate: "2021-08-03"
	},
	{
		Customer: "14",
		SalesOrganization: "5200",
		DistributionChannel: "30",
		Division: "10",
		PartnerCounter: "",
		IBAN: "",
		CardNumber: "2922873",
		PaymentCardType: "",
		BusinessPartnerName: "CHEMCOMP 2121211 sjnasj",
		CityName: "Markdorf",
		PhoneNumber: "",
		EmailAddress: "",
		DunningProcedure: "",
		DunningBlock: "",
		CustomerAccountGroup: "DEBI",
		AccountGroupName: "Customer (general)",
		FirstName: "Mo",
		LastName: "Salah",
		OrganizationBPName1: "CHEMCOMP 2121211",
		OrganizationBPName2: "sjnasj",
		GroupBusinessPartnerName1: "",
		GroupBusinessPartnerName2: "",
		BusinessPartnerType: "",
		LegalForm: "",
		LegalEntityOfOrganization: "",
		BusinessPartnerIDByExtSystem: "",
		IsMarkedForArchiving: false,
		BusinessPartnerIsBlocked: false,
		ContactPermission: "",
		StreetName: "Dornierstrasse",
		PostalCode: "88677",
		Country: "DE",
		Region: "",
		AddressTimeZone: "CET",
		POBox: "",
		POBoxPostalCode: "",
		CompanyPostalCode: "",
		CorrespondenceLanguage: "EN",
		MobilePhoneNumber: "",
		FaxNumber: "TTUIOP5O",
		PrfrdCommMediumType: "",
		SearchTerm1: "CHEMCOMP 2",
		SearchTerm2: "",
		Supplier: "",
		PostingIsBlocked: false,
		AuthorizationGroup: "",
		CreatedByUser: "SCHALKM",
		ImageUrl: "sap-icon://lead",
		TotalNetAmount: 4455,
		TransactionCurrency: "INR",
		Rating: 3,
		Progress: 30,
		OverallStatus: "C",
		StatusCriticality: 3,
		CreditScore: 800,
		LastCustomerContactDate: "2021-08-02"
	},
	{
		Customer: "16",
		SalesOrganization: "6340",
		DistributionChannel: "20",
		Division: "00",
		PartnerCounter: "",
		IBAN: "",
		CardNumber: "",
		PaymentCardType: "",
		BusinessPartnerName: " iurhgiurhgiurehgure Mehta",
		CityName: "Bangalore",
		PhoneNumber: "12345",
		EmailAddress: "fgy@xyz.example",
		DunningProcedure: "",
		DunningBlock: "",
		CustomerAccountGroup: "DEBI",
		AccountGroupName: "Customer (general)",
		FirstName: "Kevin",
		LastName: "De Bruyne",
		OrganizationBPName1: "",
		OrganizationBPName2: "",
		GroupBusinessPartnerName1: "",
		GroupBusinessPartnerName2: "",
		BusinessPartnerType: "",
		LegalForm: "",
		LegalEntityOfOrganization: "",
		BusinessPartnerIDByExtSystem: "",
		IsMarkedForArchiving: false,
		BusinessPartnerIsBlocked: false,
		ContactPermission: "",
		StreetName: "ABC street",
		PostalCode: "123456",
		Country: "IN",
		Region: "",
		AddressTimeZone: "INDIA",
		POBox: "123",
		POBoxPostalCode: "54678",
		CompanyPostalCode: "",
		CorrespondenceLanguage: "EN",
		MobilePhoneNumber: "+5398706543",
		FaxNumber: "",
		PrfrdCommMediumType: "INT",
		SearchTerm1: "MEHTA",
		SearchTerm2: "",
		Supplier: "",
		PostingIsBlocked: false,
		AuthorizationGroup: "",
		CreatedByUser: "PARMARDE",
		ImageUrl: "sap-icon://lab",
		TotalNetAmount: 90012,
		TransactionCurrency: "EUR",
		Rating: 4,
		Progress: 40,
		OverallStatus: "A",
		StatusCriticality: 0,
		CreditScore: 400
	},
	{
		Customer: "17",
		SalesOrganization: "8930",
		DistributionChannel: "40",
		Division: "22",
		PartnerCounter: "",
		IBAN: "",
		CardNumber: "",
		PaymentCardType: "",
		BusinessPartnerName: "Toll Industries Customer",
		CityName: "Walldorf",
		PhoneNumber: "09123 12312333",
		EmailAddress: "back.stage@xyz.example",
		DunningProcedure: "",
		DunningBlock: "",
		CustomerAccountGroup: "DEBI",
		AccountGroupName: "Customer (general)",
		FirstName: "Eden",
		LastName: "Hazard",
		OrganizationBPName1: "Toll Industries Customer",
		OrganizationBPName2: "",
		GroupBusinessPartnerName1: "",
		GroupBusinessPartnerName2: "",
		BusinessPartnerType: "",
		LegalForm: "",
		LegalEntityOfOrganization: "",
		BusinessPartnerIDByExtSystem: "",
		IsMarkedForArchiving: false,
		BusinessPartnerIsBlocked: false,
		ContactPermission: "",
		StreetName: "Nebengasse",
		PostalCode: "69190",
		Country: "DE",
		Region: "",
		AddressTimeZone: "CET",
		POBox: "",
		POBoxPostalCode: "",
		CompanyPostalCode: "",
		CorrespondenceLanguage: "DE",
		MobilePhoneNumber: "+49934234234234",
		FaxNumber: "08837",
		PrfrdCommMediumType: "",
		SearchTerm1: "ACR",
		SearchTerm2: "",
		Supplier: "",
		PostingIsBlocked: false,
		AuthorizationGroup: "",
		CreatedByUser: "CORNELIUSRI",
		ImageUrl: "sap-icon://building",
		TotalNetAmount: 12324,
		TransactionCurrency: "USD",
		Rating: 5,
		Progress: 0,
		OverallStatus: "B",
		StatusCriticality: 1,
		CreditScore: 700
	}
];

const getCustomerTypeData = function (keys) {
	var data;
	if (keys) {
		data = aCustomerData.find(function (oCustomer) {
			return Object.keys(keys).every(function (key) {
				return !oCustomer[key] || oCustomer[key] === keys[key];
			});
		});
	} else if (keys === undefined) {
		data = aCustomerData;
	}
	return data;
};

module.exports = {
	executeAction: async function (actionDef, actionData, keys) {
		if (actionDef.name === "UnBlockBusinessPartner") {
			if (actionData.PaymentBlockingReason) {
				var oCustomer = getCustomerTypeData(keys);
				for (var keyName in keys) {
					oCustomer[keyName] = keys[keyName];
				}
				oCustomer.PaymentBlockingReason = actionData.PaymentBlockingReason;
				oCustomer.BusinessPartnerIsBlocked = false;
				return oCustomer;
			}
		}
		if (actionDef.name === "BoundActionIP") {
			if (actionData.FullName) {
				this.throwError(
					"",
					204,
					[{ code: "BOUND_ACTION_MSG", message: "Bound Action with full name " + actionData.FullName, numericSeverity: 1 }],
					true
				);
			}
		}
		if (actionDef.name === "DummyStaticAction") {
			if (actionData.MessageText) {
				this.throwError(
					"",
					204,
					[
						{
							code: "STATIC_ACTION_MSG",
							message: "Static Action with messagetext: " + actionData.MessageText,
							numericSeverity: 1
						}
					],
					true
				);
			}
		}
		if (actionDef.name === "DummyStaticActionIP") {
			if (actionData.MessageText) {
				this.throwError(
					"",
					204,
					[
						{
							code: "STATIC_ACTION_MSG",
							message: "Static Action with messagetext: " + actionData.MessageText,
							numericSeverity: 1
						}
					],
					true
				);
			}
		}
	},

	fetchEntries: async function (keyValues) {
		const code = keyValues["P_CompanyCode"];
		const currencyCode = keyValues["CurrencyCode"];

		return [
			{
				P_CompanyCode: code,
				Set: getCustomerTypeData().map(function (oCustomer) {
					oCustomer["CompanyCode"] = code;
					oCustomer["Currency"] = currencyCode;
					return oCustomer;
				})
			}
		];
	},
	getInitialDataSet: function (contextId) {
		return [
			{
				P_CompanyCode: "001",
				Set: [
					{
						Customer: "##1",
						CompanyCode: "001",
						SalesOrganization: "",
						DistributionChannel: "",
						Division: "",
						PartnerCounter: "",
						IBAN: "",
						CardNumber: "",
						PaymentCardType: "",
						BusinessPartnerName: ""
					},
					{
						Customer: "1",
						CompanyCode: "001",
						SalesOrganization: "",
						DistributionChannel: "",
						Division: "",
						PartnerCounter: "",
						IBAN: "",
						CardNumber: "",
						PaymentCardType: "",
						BusinessPartnerName: "TEST asdf"
					},
					{
						Customer: "2",
						CompanyCode: "001",
						SalesOrganization: "",
						DistributionChannel: "",
						Division: "",
						PartnerCounter: "",
						IBAN: "",
						CardNumber: "",
						PaymentCardType: "",
						BusinessPartnerName: ""
					},
					{
						Customer: "2",
						CompanyCode: "001",
						SalesOrganization: "",
						DistributionChannel: "",
						Division: "",
						PartnerCounter: "",
						IBAN: "",
						CardNumber: "",
						PaymentCardType: "",
						BusinessPartnerName: ""
					},
					{
						Customer: "6",
						CompanyCode: "001",
						SalesOrganization: "",
						DistributionChannel: "",
						Division: "",
						PartnerCounter: "",
						IBAN: "",
						CardNumber: "",
						PaymentCardType: "",
						BusinessPartnerName: ""
					},
					{
						Customer: "11",
						CompanyCode: "001",
						SalesOrganization: "",
						DistributionChannel: "",
						Division: "",
						PartnerCounter: "",
						IBAN: "",
						CardNumber: "",
						PaymentCardType: "",
						BusinessPartnerName: ""
					},
					{
						Customer: "11",
						CompanyCode: "001",
						SalesOrganization: "0001",
						DistributionChannel: "01",
						Division: "01",
						PartnerCounter: "",
						IBAN: "",
						CardNumber: "",
						PaymentCardType: "",
						BusinessPartnerName: ""
					},
					{
						Customer: "12",
						CompanyCode: "001",
						SalesOrganization: "",
						DistributionChannel: "",
						Division: "",
						PartnerCounter: "",
						IBAN: "",
						CardNumber: "",
						PaymentCardType: "",
						BusinessPartnerName: " Thomas Tester"
					},
					{
						Customer: "16",
						CompanyCode: "001",
						SalesOrganization: "",
						DistributionChannel: "",
						Division: "",
						PartnerCounter: "",
						IBAN: "",
						CardNumber: "",
						PaymentCardType: "",
						BusinessPartnerName: " xpm-01 xqp"
					},
					{
						Customer: "17",
						CompanyCode: "001",
						SalesOrganization: "",
						DistributionChannel: "",
						Division: "",
						PartnerCounter: "",
						IBAN: "",
						CardNumber: "",
						PaymentCardType: "",
						BusinessPartnerName: "xpm-02 as"
					}
				]
			}
		];
	}
};
